# Fill with real values before init.
bucket                      = ""
key                         = "state/dev/terraform.tfstate"
region                      = "us-east-1"
endpoint                    = ""
access_key                  = ""
secret_key                  = ""
skip_credentials_validation = true
skip_metadata_api_check     = true
skip_region_validation      = true
skip_requesting_account_id  = true
use_path_style              = true

