apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  labels:
    environment: prod
spec:
  project: default
  source:
    repoURL: https://github.com/Fauxx/FireMonitoringSystem
    targetRevision: main
    path: infrastructure/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
