services:
  db:
    restart: always
    volumes:
      - db_prod_data:/var/lib/postgresql/data

  influx:
    restart: always

  grafana:
    restart: always
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: false

  api:
    restart: always
    environment:
      NODE_ENV: production

  nginx:
    ports:
      - "80:80"
      - "443:443"
    restart: always

  mqtt:
    restart: always

volumes:
  db_prod_data: