output "cluster_id" {
  value       = azurerm_kubernetes_cluster.this.id
  description = "AKS cluster resource ID"
}

output "cluster_name" {
  value       = azurerm_kubernetes_cluster.this.name
  description = "AKS cluster name"
}

output "cluster_endpoint" {
  value       = azurerm_kubernetes_cluster.this.kube_config.0.host
  description = "AKS cluster API server endpoint"
}

output "cluster_ca_certificate" {
  value       = azurerm_kubernetes_cluster.this.kube_config.0.cluster_ca_certificate
  description = "AKS cluster CA certificate"
}

output "oidc_issuer_url" {
  value       = azurerm_kubernetes_cluster.this.oidc_issuer_url
  description = "OIDC issuer URL for the AKS cluster"
}

output "kubelet_identity_object_id" {
  value       = azurerm_kubernetes_cluster.this.kubelet_identity.0.object_id
  description = "Object ID of the kubelet identity"
}

output "node_resource_group" {
  value       = azurerm_kubernetes_cluster.this.node_resource_group
  description = "Resource group generated by AKS containing the cluster nodes"
}
