apiVersion: 1

datasources:
  - name: Fire Monitoring InfluxDB
    type: influxdb
    uid: influxdb-fire
    access: proxy
    url: http://influx:8086
    isDefault: true
    editable: false
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: false
    secureJsonData:
      token: ${INFLUXDB_TOKEN}