# Persistence saves data to the volume in your tree
persistence true
persistence_location /mosquitto/data/

# Logging helps you debug if the ESP32 fails to connect
log_dest file /mosquitto/log/mosquitto.log

# Standard MQTT Port
listener 1883
allow_anonymous true  # Change to false later for security