apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db/statefulset.yaml
  - db/service.yaml
  - db/configmap.yaml 
  - db/exporter.yaml
  - influx/statefulset.yaml
  - influx/service.yaml
  - mqtt/deployment.yaml
  - mqtt/service.yaml
  - mqtt/exporter.yaml
  - telegraf/deployment.yaml
  - flyway/job.yaml
  - api/deployment.yaml
  - api/service.yaml
  - etl/deployment.yaml
  - dashboard/deployment.yaml
  - dashboard/service.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
  - grafana/pvc.yaml
  - loki/deployment.yaml
  - loki/service.yaml
  - loki/pvc.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  - prometheus/pvc.yaml
  - node-exporter/daemonset.yaml
  - node-exporter/service.yaml
  - cadvisor/daemonset.yaml
  - cadvisor/service.yaml
  - alloy/daemonset.yaml
  - ingress

configMapGenerator:
  - name: mqtt-config
    files:
      - mosquitto.conf=mqtt/config/mosquitto.conf
  - name: telegraf-config
    files:
      - telegraf.conf=telegraf/telegraf.conf
  - name: prometheus-config
    files:
      - prometheus.yml=prometheus/prometheus.yml
  - name: loki-config
    files:
      - local-config.yaml=loki/local-config.yaml
  - name: alloy-config
    files:
      - config.alloy=alloy/config.alloy
  - name: grafana-provisioning
    files:
      - dashboards.yaml=grafana/provisioning/dashboards/fire-dashboards.yaml
      - influxdb.yaml=grafana/provisioning/datasources/influxdb.yaml
      - loki.yaml=grafana/provisioning/datasources/loki.yaml
      - prometheus.yaml=grafana/provisioning/datasources/prometheus.yaml
  - name: grafana-dashboards-telemetry
    files:
      - fire-main.json=grafana/dashboards/telemetry/fire-main.json
  - name: grafana-dashboards-infrastructure
    files:
      - cluster-health.json=grafana/dashboards/infrastructure/cluster-health.json
  - name: grafana-dashboards-application
    files:
      - api-performance.json=grafana/dashboards/application/api-performance.json
      - loki-error-logs.json=grafana/dashboards/application/loki-error-logs.json
  - name: grafana-dashboards-datalayer
    files:
      - postgres-health.json=grafana/dashboards/data-layer/postgres-health.json
      - mqtt-broker.json=grafana/dashboards/data-layer/mqtt-broker.json
  - name: dashboard-nginx-config
    files:
      - default.conf=dashboard/nginx.conf