resource_group_name  = "rg-firemonitoring-tfstate-01"
storage_account_name = "stfiremonitortfstate"
container_name       = "tfstate"
use_azuread_auth     = true
key                  = "aks-dev/02-platform/terraform.tfstate"
