apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fire-monitoring-dev

resources:
  - ../../base

images:
  - name: api
    newName: ghcr.io/fauxx/firemonitoringsystem/api
    newTag: latest
  - name: etl-processor
    newName: ghcr.io/fauxx/firemonitoringsystem/etl-processor
    newTag: latest
  - name: dashboard
    newName: ghcr.io/fauxx/firemonitoringsystem/dashboard
    newTag: latest

