apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fire-monitoring-dev

configMapGenerator:
- name: fire-monitoring-config
  behavior: replace
  envs:
    - dev-public.env

resources:
- ../../base


images:
- name: api
  newName: ghcr.io/fauxx/firemonitoringsystem/api
  newTag: 53938bf
- name: dashboard
  newName: ghcr.io/fauxx/firemonitoringsystem/dashboard
  newTag: 53938bf
- name: etl-processor
  newName: ghcr.io/fauxx/firemonitoringsystem/etl-processor
  newTag: 53938bf

labels:
- includeSelectors: true
  pairs:
    deployment-type: development
    environment: dev
patches:
- path: ingress-patch.yaml
