{
 "title": "API Performance",
 "tags": [ "application" ],
 "refresh": "30s",
 "panels": [
  {
   "title": "Throughput (RPS)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status_code=~\"2..\"}[1m])) / sum(rate(http_request_duration_seconds_count[1m])) * 100"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status_code=~\"5..\"}[1m]))"
    }
   ]
  },
  {
   "title": "p95 Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Throughput (RPS) Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Latency Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95 Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99 Latency"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) / sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "Average Latency"
    }
   ]
  },
  {
   "title": "Throughput by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[5m])) by (status_code)",
     "legendFormat": "HTTP {{status_code}}"
    }
   ]
  },
  {
   "title": "Throughput by Route Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}