apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ops
  annotations:
    nginx.ingress.kubernetes.io/app-root: /grafana
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ops.fires.systems
      secretName: grafana-ops-tls
  rules:
    - host: ops.fires.systems
      http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
