apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fire-monitoring-prod

generatorOptions:
  annotations:
    argocd.argoproj.io/hook: PreSync

configMapGenerator:
- behavior: replace
  envs:
  - prod-public.env
  name: fire-monitoring-config

resources:
- ../../base
- grafana-ops-ingress.yaml
- collaboration-rbac.yaml

patchesStrategicMerge:
- ingress-patch.yaml
- api-replicas-patch.yaml
- dashboard-replicas-patch.yaml

images:
- name: api
  newName: ghcr.io/fauxx/firemonitoringsystem/api
  newTag: 02aa627
- name: etl-processor
  newName: ghcr.io/fauxx/firemonitoringsystem/etl-processor
  newTag: ea30f64
- name: dashboard
  newName: ghcr.io/fauxx/firemonitoringsystem/dashboard
  newTag: fc08adf
- name: db-migrations
  newName: ghcr.io/fauxx/firemonitoringsystem/db-migrations
  newTag: a4eb2ae

commonLabels:
  deployment-type: production
  environment: prod
