apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migrate
  labels:
    app: flyway
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation, HookSucceeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: flyway
    spec:
      serviceAccountName: flyway-sa
      restartPolicy: OnFailure
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-proxy/v2.8.2:latest
          args:
            - "--auto-iam-authn"
            - "--quitquitquit"
            - "firemonitoring-dev:asia-east1:firemonitoring-dev-db"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 10m
              memory: 128Mi
        - name: flyway
          image: db-migrations
          envFrom:
            - configMapRef:
                name: fire-monitoring-config
            - secretRef:
                name: fire-monitoring-secrets
          env:
            - name: FLYWAY_URL
              value: "jdbc:postgresql://127.0.0.1:5432/firemonitoring_dev"
            - name: FLYWAY_USER
              value: "sa-api-database-client@firemonitoring-dev.iam"
          args: ["-connectRetries=60", "migrate"]

