apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migrate
  labels:
    app: flyway
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation, HookSucceeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: flyway
    spec:
      serviceAccountName: flyway-sa
      restartPolicy: OnFailure
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.3
          args:
            - "--auto-iam-authn"
            - "--quitquitquit"
            - "$(CLOUD_SQL_CONNECTION_NAME)"
          env:
            - name: CLOUD_SQL_CONNECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: fire-monitoring-config
                  key: CLOUD_SQL_CONNECTION_NAME
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 10m
              memory: 128Mi
        - name: flyway
          image: db-migrations
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: fire-monitoring-config
            - secretRef:
                name: fire-monitoring-secrets
          env:
            - name: FLYWAY_URL
              value: "jdbc:postgresql://127.0.0.1:5432/firemonitoring_dev"
            - name: FLYWAY_USER
              valueFrom:
                configMapKeyRef:
                  name: fire-monitoring-config
                  key: CLOUD_SQL_IAM_USER
          args: ["-connectRetries=60", "migrate"]
