name: "Debug CI"
on:
  push:
    branches: [ debug-ci ]
jobs:
  test:
    uses: ./.github/workflows/gcp-terraform-reusable.yml
    with:
      environment: gke-dev
      layer_dir: infrastructure/terraform/environments/gke-dev/01-infra
      execution_mode: plan-only
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      CLOUDFLARE_TUNNEL_CREDENTIALS_JSON: ${{ secrets.CLOUDFLARE_TUNNEL_CREDENTIALS_JSON }}
