name: "Debug CI"
on:
  push:
    branches: [ debug-ci ]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
  test:
    needs: setup
    uses: ./.github/workflows/gcp-terraform-reusable.yml
    with:
      environment: gke-dev
      layer_dir: infrastructure/terraform/environments/gke-dev/01-infra
      execution_mode: plan-only
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
